
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\markc\Desktop\Programming\decode\build\assets\frame2")


def assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("992x594")
window.configure(bg = "#F5F5F5")


canvas = Canvas(
    window,
    bg = "#F5F5F5",
    height = 594,
    width = 992,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    992.0,
    76.0,
    fill="#003049",
    outline="")

canvas.create_text(
    128.0,
    29.0,
    anchor="nw",
    text="Police Clearance  Issuance System",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    69.0,
    106.0,
    anchor="nw",
    text="Create a Clearance",
    fill="#000000",
    font=("Inter Bold", 30 * -1)
)

button_image_1 = PhotoImage(
    file=assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=520.0,
    y=281.0,
    width=403.0,
    height=277.0
)

button_image_2 = PhotoImage(
    file=assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=69.0,
    y=281.0,
    width=403.0,
    height=277.0
)

canvas.create_text(
    104.0,
    156.0,
    anchor="nw",
    text="Wanted Verification",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    320.0,
    156.0,
    anchor="nw",
    text="Client Information",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    508.0,
    156.0,
    anchor="nw",
    text="Issuance",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

image_image_1 = PhotoImage(
    file=assets("image_1.png"))
image_1 = canvas.create_image(
    283.0,
    96.0,
    image=image_image_1
)

canvas.create_text(
    69.0,
    237.0,
    anchor="nw",
    text="2. Once check and the client is not on the wanted list, get the client information.",
    fill="#000000",
    font=("Inter Regular", 14 * -1)
)

canvas.create_text(
    69.0,
    256.0,
    anchor="nw",
    text="3. Issue a clearance.",
    fill="#000000",
    font=("Inter Regular", 14 * -1)
)

canvas.create_text(
    69.0,
    216.0,
    anchor="nw",
    text="1. Verify first the client to check if he/she is on the wanted list.",
    fill="#000000",
    font=("Inter Regular", 14 * -1)
)

canvas.create_text(
    69.0,
    193.0,
    anchor="nw",
    text="Steps in creating a clearance.",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

button_image_3 = PhotoImage(
    file=assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=874.0,
    y=26.0,
    width=62.0,
    height=21.0
)

button_image_4 = PhotoImage(
    file=assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=772.0,
    y=26.0,
    width=62.0,
    height=21.0
)

button_image_5 = PhotoImage(
    file=assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=874.0,
    y=26.0,
    width=62.0,
    height=21.0
)

button_image_6 = PhotoImage(
    file=assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=772.0,
    y=26.0,
    width=62.0,
    height=21.0
)
window.resizable(False, False)
window.mainloop()
